### ISSUE TITLE
Use pipeline-library to automatically publish docker image

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/account-app#134]
- [x] Apply https://github.com/jenkins-infra/pipeline-library/blob/master/resources/io/jenkins/infra/docker/README.adoc 
- [x] Add repository to infra.ci (either rename it as `docker-account-app` or amend [infra.ci's config](https://github.com/jenkins-infra/kubernetes-management/blob/644e9727ba3763f0e891e926e6fc85c63c3a8e82/config%2Fjenkins-infra.yaml#L344) )

**Comment by dduportal** [comment]
> Add repository to infra.ci (either rename it as docker-account-app or amend [infra.ci's config](https://github.com/jenkins-infra/kubernetes-management/blob/644e9727ba3763f0e891e926e6fc85c63c3a8e82/config%2Fjenkins-infra.yaml#L344) )

https://github.com/jenkins-infra/kubernetes-management/pull/2715

**Comment by dduportal** [comment]
>  Apply https://github.com/jenkins-infra/pipeline-library/blob/master/resources/io/jenkins/infra/docker/README.adoc

#137

**Comment by dduportal** [comment]
Reopening: we need a release-drafter setup to publish proper GitHub releases associated with tag (or the build are failing)

**Comment by lemeurherve** [comment]
Shouldn't a patch to the pipeline library be added instead to avoid failing when there isn't any release ?

**Comment by dduportal** [comment]
> Shouldn't a patch to the pipeline library be added instead to avoid failing when there isn't any release ?

Yes, but I remember that you had some issues when trying to implement this so I assumed that it's easier to create the release-drafter config once in a while instead. I might mis-remember though (but add ing release-drafter is ... easy).

**Comment by dduportal** [comment]
Fixed by #138
