### ISSUE TITLE
navbar should link to account app not Jenkins.io

### ISSUE THREAD

**Issue by timja** [jenkins-infra/account-app#149]
Currently there's no way to navigate out of error pages, and clicking the 'home link' in the nav bar takes you to Jenkins.io

I think each app should be linked to from the home page not Jenkins.io

any thoughts @halkeye ?

**Comment by halkeye** [comment]
home = top right corner? Make an issue on https://github.com/halkeye/jenkins-io-components its on my local issues to address. I think top right should goto the "property" url. or maybe an overriden homeurl
