### ISSUE TITLE
Footer blocks page content

### ISSUE THREAD

**Issue by NotMyFault** [jenkins-infra/account-app#250]
### Problem with this page

https://accounts.jenkins.io/login

### Expected behavior

The footer is not on top of page content.

### Actual behavior

The footer is on top of page content.

![Screenshot 2023-03-28 at 20 07 51](https://user-images.githubusercontent.com/13383509/228329012-bc8b20c3-fa3d-4a70-96f9-403f80a00301.png)

**Comment by lemeurherve** [comment]
Removing jenkins-io-component in the footer didn't fix the issue, reopening
