### ISSUE TITLE
Jenkins login issues  account not populating 

### ISSUE THREAD

**Issue by carolynrenahuggins** [jenkins-infra/account-app#269]
### Problem with this page

[Your Profile | Jenkins](https://accounts.jenkins.io/myself/) page

### Expected behavior

The expected behavior is the accounts page was supposed to populate  where I can build check builds added webhooks for my MS Teams account and add the connector for Ms teams It is not giving me the account page 

### Actual behavior

Hello I installed jenkins on a new server with azure Iadded my azure crditials at log in for the jenkins password  I have a differnet pass word for the login page for jenkins it would not let me added it when I was finally able to get logged in but it will only populate the the profile on my page ![image](https://github.com/jenkins-infra/account-app/assets/65857024/64ec1f8c-0a27-4c0f-9b87-fdb186ad2d38)

[My Account](https://accounts.jenkins.io/)
[Profile](https://accounts.jenkins.io/myself)
[Logout ](https://accounts.jenkins.io/logout)
Account
You can create/manage your user account that you use for accessing [Jira](https://issues.jenkins.io/), [Artifactory](https://repo.jenkins-ci.org/), VPN and other services within the [Jenkins Infrastructure](https://www.jenkins.io/projects/infrastructure).

[Profile](https://accounts.jenkins.io/myself) - View and edit profile, change password, etc.
[Logout](https://accounts.jenkins.io/logout)

### Possible solution

I had another server that i terminated with azure stated another which is the one im working from now the first was not acting as expected i could only see that builds were successful but no information populated It was done with my fresh works account 

although I did have the account page

**Comment by dduportal** [comment]
Hi @carolynrenahuggins , this repository hosts the code for the application served under https://accounts.jenkins.io whihc which allos managing account for the `jenkins.io` websites (mainly Jenkins's source code contributors and plugin maintainers).

It's not aimed for individual Jenkins instances at all: it eplains why the informations you've put in accounts.jenkins.io are not visible in your own Jenkins instance.

As such, I'll close this issue as it is not a problem related to the account-app application code, neither with the Jenkins infrasructure (`*jenkins.io` websites).

You should open a thread in the community forums at community.jenkins.io to get started and ask fro help in setting up your Jenkins instance.

Please note, that if you follow the  Jenkins configuration wizard, a default `admin` user is created (see https://www.jenkins.io/doc/pipeline/tour/getting-started/).

Jenkins has its own authentication realm for storing users by default, but can be extended to delegate authentication to an external system, using plugins from https://plugins.jenkins.io, such as [Azure AD](https://plugins.jenkins.io/azure-ad/), [SAML](https://plugins.jenkins.io/saml/), [LDAP](https://plugins.jenkins.io/ldap/) and many more.

Also, you might be interested by https://www.jenkins.io/doc/book/security/. Good luck in your journey and do not hesitate to ask in the community forums!

aks-syspool-23443997-vmss000004-privatek8s

**Comment by carolynrenahuggins** [comment]
Thanks for your response
