### ISSUE TITLE
singin 

### ISSUE THREAD

**Issue by sasha1819** [jenkins-infra/account-app#363]
### Problem with this page

[Sign up | Jenkins](https://accounts.jenkins.io/signup) page

### Expected behavior

after I fill my name and the password I should be able to see the Mine page 

### Actual behavior

i reserved Invalid username or password Sign in to Jenkins

**Comment by dduportal** [comment]
This issue tracker is **only** aimed at the web application itself (not at its production deployment and usage).

Could you open an issue in the https://github.com/jenkins-infra/helpdesk tracker (and gives us details: which username and email do you use so we can search logs, event and database to help you)
